
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - syncer.k8s.kfirs.com
  resources:
  - syncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncer.k8s.kfirs.com
  resources:
  - syncers/finalizers
  verbs:
  - update
- apiGroups:
  - syncer.k8s.kfirs.com
  resources:
  - syncers/status
  verbs:
  - get
  - patch
  - update
