# permissions for end users to edit syncers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syncer-editor-role
rules:
- apiGroups:
  - syncer.k8s.kfirs.com
  resources:
  - syncer2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syncer.k8s.kfirs.com
  resources:
  - syncers/status
  verbs:
  - get
