# permissions for end users to view syncers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syncer-viewer-role
rules:
- apiGroups:
  - syncer.k8s.kfirs.com
  resources:
  - syncers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - syncer.k8s.kfirs.com
  resources:
  - syncers/status
  verbs:
  - get
