name: Build
on:
  push:
    branches: ["**"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: europe-docker.pkg.dev/arikkfir/public/syncer
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: arikkfir
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Authenticate to Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Build image
        run: docker build -t ${IMAGE}:${GITHUB_SHA} .
      - name: Push image
        run: docker push ${IMAGE}:${GITHUB_SHA}
