name: Docker

on:
  workflow_run:
    workflows: ["verify"]
    branches: [main]
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make docker-push
