name: Push

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make test

    - name: Build image
      run: make docker-build
      env:
        VERSION: ${{ github.sha }}

    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: arikkfir
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: info

#    - name: Push image
#      run: make docker-build
#      env:
#        VERSION: ${{ github.sha }}
#        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
