name: Push

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/') }}
    env:
      IMAGE: europe-docker.pkg.dev/arikkfir/public/syncer
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: arikkfir
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Authenticate to Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Build image
        run: docker build -t ${IMAGE}:${GITHUB_SHA} .
      - name: Push image
        run: docker push ${IMAGE}:${GITHUB_SHA}

  tag:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/tags/') }}
    env:
      IMAGE: europe-docker.pkg.dev/arikkfir/public/syncer
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: arikkfir
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Authenticate to Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Pull image
        run: docker pull ${IMAGE}:${GITHUB_SHA}
      - name: Retag image
        run: docker tag ${IMAGE}:${GITHUB_SHA} ${IMAGE}:${GITHUB_REF/refs\/tags\//}
      - name: Push image
        run: docker push ${IMAGE}:${IMAGE}:${GITHUB_REF/refs\/tags\//}
