name: Push

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: europe-docker.pkg.dev/arikkfir/public/syncer:${GITHUB_SHA}
    steps:

      ### SETUP ###

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: arikkfir
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate to Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev

      ### BUILD ###

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Build image
        run: docker build -t ${IMAGE} .

      - name: Push image
        run: docker push ${IMAGE}
