name: Push

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make test

    - name: Build image
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: arikkfir
        APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
#        VERSION: ${{ github.sha }}
      with:
        cli: docker
        args: build -t europe-docker.pkg.dev/arikkfir/public/syncer:${{ github.sha }}
#      run: make docker-build

    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: arikkfir
        APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      with:
        args: auth configure-docker europe-docker.pkg.dev

#    - name: Push image
#      run: make docker-push
#      env:
#        VERSION: ${{ github.sha }}
