name: Unpublish

on:
  release:
    types: [unpublished]

jobs:

  unpublish:
    runs-on: ubuntu-latest
    env:
      IMAGE: europe-docker.pkg.dev/arikkfir/public/syncer
    steps:

      ### SETUP ###

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: arikkfir
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate to Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev

      ### BUILD ###

      - name: Delete tag
        run: gcloud artifacts docker tags delete ${IMAGE}:${GITHUB_REF}
