name: Publish

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: europe-docker.pkg.dev/arikkfir/public/syncer
    steps:

      ### SETUP ###

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: arikkfir
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate to Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev

      ### BUILD ###

      - name: Pull image
        run: docker pull ${IMAGE}:${GITHUB_SHA}

      - name: Retag image
        run: docker tag ${IMAGE}:${GITHUB_SHA} ${IMAGE}:${GITHUB_REF}

      - name: Push image
        run: docker push ${IMAGE}:${GITHUB_REF}
