name: Self
on:
  push:
    branches: [self-hosted]
jobs:
  build:
    runs-on: self-hosted
    env:
      IMAGE: europe-docker.pkg.dev/arikkfir/public/syncer
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Build image
        run: docker build -t ${IMAGE}:${GITHUB_SHA} .
      - name: Push image
        run: docker push ${IMAGE}:${GITHUB_SHA}

