name: Tag
on:
  push:
    tags: ["**"]
jobs:
  tag:
    runs-on: self-hosted
    env:
      IMAGE: europe-docker.pkg.dev/arikkfir/public/syncer
    steps:
      - run: docker pull ${IMAGE}:${GITHUB_SHA}
      - run: docker tag ${IMAGE}:${GITHUB_SHA} ${IMAGE}:${GITHUB_REF/refs\/tags\//}
      - run: docker push ${IMAGE}:${GITHUB_REF/refs\/tags\//}
